// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCTYY7fjiGc8UnMTZC2GeuNVoJrePM9Sc',
    appId: '1:1024325751774:web:181af02652043256d6c34f',
    messagingSenderId: '1024325751774',
    projectId: 'social-media-application-a3aa8',
    authDomain: 'social-media-application-a3aa8.firebaseapp.com',
    storageBucket: 'social-media-application-a3aa8.appspot.com',
    measurementId: 'G-2BM41NNNSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEQYQGpPaclCaMG1GVz92y5t-0BZkcOOo',
    appId: '1:1024325751774:android:9b7cea2f852413f3d6c34f',
    messagingSenderId: '1024325751774',
    projectId: 'social-media-application-a3aa8',
    storageBucket: 'social-media-application-a3aa8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG7rDomR1sIbl797mhjf3TwFM58SzSuTw',
    appId: '1:1024325751774:ios:c9a16bc2f89ac9afd6c34f',
    messagingSenderId: '1024325751774',
    projectId: 'social-media-application-a3aa8',
    storageBucket: 'social-media-application-a3aa8.appspot.com',
    iosClientId: '1024325751774-7car8s5g0k5l2j1fnthdbjljdeajp2j2.apps.googleusercontent.com',
    iosBundleId: 'com.example.techMedia',
  );
}
